name: uavbook
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - numpy
    - matplotlib
    - jupyter
    - scipy
    - opencv
    - pillow
    - pip:
        - pyqtgraph
        - pyqt6
        - PyOpenGL
        - PyOpenGL_accelerate
        - pynput
        - python-dotenv
